name: Test multi-arch
run-name: ${{ github.actor }} is running multi-arch tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        alpine-arch: [ 'x86_64', 'x86', 'aarch64', 'armhf', 'armv7', 'ppc64le', 'riscv64', 's390x' ]
    name: alpine latest-stable ${{ matrix.alpine-arch }} / Python3.x
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.alpine-arch }}
          version: latest-stable
          packages: build-base python3 py3-pip python3-dev
      - name: Install cbrrr python module
        run: |
          python3 -m venv .venv
          .venv/bin/python3 -m pip install -v .[fixtures]
        shell: alpine.sh {0}
      - name: Run the tests
        run: |
          .venv/bin/python3 -m unittest -v
        shell: alpine.sh {0}
