name: Test multi-python-version
run-name: ${{ github.actor }} is running multi-python-version tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13' ]
    name: ubuntu-latest Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install cbrrr python module
        run: |
          python3 -m pip install -v .[fixtures]
      - name: Run the tests
        run: |
          python3 -m unittest -v
