name: Run tests
run-name: ${{ github.actor }} is running tests
on: push
jobs:
  Build-Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install cbrrr python module
        run: |
          python3 -m pip install -v .
      - name: Run the tests
        run: |
          python3 -m unittest -v
