name: Run tests
run-name: ${{ github.actor }} is running tests
on: push
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11', '3.12' ]
        arch: [ 'x64', 'arm64' ]
    name: Python ${{ matrix.python-version }} on ${{ matrix.arch }} tests
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
      - name: Install cbrrr python module
        run: |
          python3 -m pip install -v .[fixtures]
      - name: Run the tests
        run: |
          python3 -m unittest -v
