name: Run tests
run-name: ${{ github.actor }} is running tests
on: push
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install cbrrr python module
        run: |
          python3 -m pip install -v .[fixtures]
      - name: Run the tests
        run: |
          python3 -m unittest -v
